#!/usr/bin/env bash
set -e

bin_dir="$(dirname "$0")"
note_dir="$(dirname "$bin_dir")/notes"

# Ensure that the notes directory exists.
mkdir -p "$note_dir"

# Search through titles.
target=$(
    find "$note_dir" \
        | grep .md$ \
        | sort -r \
        | xargs -E '\n' -I {} grep '^# ' -H -n {} \
        | sed 's/\(.*\)\([0-9]\{2\}-[0-9]\{2\}-[0-9]\{4\}\).md:\([0-9]\{1\}\):# \(.*\)/\2:\3 \4/' \
        | fzf --no-sort -i --preview "echo {} | sed 's|\([0-9]\{2\}-[0-9]\{2\}-[0-9]\{4\}\):\([0-9]\{1,\}\) \(.*\)|'$note_dir'\/\1\.md|' | xargs cat"

)

# Extract date and line number from match.
date=$(echo $target | sed 's/\([0-9]\{2\}-[0-9]\{2\}-[0-9]\{4\}\):\([0-9]\{1,\}\) \(.*\)/\1/')
line=$(echo $target | sed 's/\([0-9]\{2\}-[0-9]\{2\}-[0-9]\{4\}\):\([0-9]\{1,\}\) \(.*\)/\2/')

# Open vim at match.
vim +$line -c 'execute "normal zR"' "$note_dir/$date.md"

